### PR TITLE
Add rpc call from BCI to get neighbor's info

### LINKED ISSUE #31: Node query local information from its' neighbors
Node query local information from its' neighbors.

#8

### PR DESCRIPTION
**Pull request by Plane-walker**
Add rpc call from BCI to get neighbor's info.

close #31

### CODE REVIEW

**Review by Bay1997 — COMMENTED** [review]
Add requests module into README.md

**Comment by Plane-walker** [comment]
> Add requests module into README.md

Requests is in python standard library.

**Comment by Bay1997** [comment]
> 
image

**Comment by Plane-walker** [comment]
> > 
> 
> image

image

**Comment by Plane-walker** [comment]
> > 
> 
> image

I made a mistake, requests is auto installed by conada. 😭

**Comment by Bay1997** [comment]
> > image
> 
> image

Ref [this](https://docs.python-requests.org/en/latest/user/install/#install) and (this)[https://www.liaoxuefeng.com/wiki/1016959663602400/1183249464292448] make sure in (this)[https://docs.python-requests.org/en/latest/user/quickstart/#make-a-request], this package may be installed in Anaconda or other environment but it is not in python standard library.

**Review by Bay1997 — APPROVED** [review]

**Review by quincysky — APPROVED** [review]

**Pull request merged**
